### ISSUE TITLE
Issue 1: User can play songs from collection of music

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/acnh-bgm#1]
## 💰 Functionality

Users can listen to all the different hourly background songs from the soundtrack of Animal Crossing: New Horizon.

## 🖼️ Wireframes

<img width="723" alt="image" src="https://user-images.githubusercontent.com/110082070/203443020-efc711aa-0e63-495f-9500-d0ce0f31d11b.png">

## ✅ Task List

- [x] Make a XMLHttpRequest to obtain all of the specific songs needed from the ACNH api. 
- [x] Assign value of of the response object in array form to a new variable arrayOfSongs.
- [x] Loop through the arrayOfSongs to obtain link for each audio file
- [x] Create a DOM tree for list element that will represent each audio file.
- [x] Create a image element to append to list element with source set to a relative file path
- [x] Loop through the same arrayOfSongs to find all the 'file-name' property values
- [x] Define two functions in the global scale to create new title for each song by re-arranging the text data from each song's 'file-name' property for easier readability. 
- [x] Create an audio element with 'controls' attribute set with no value
- [x] Set attribute of new audio element to audio file found in 'music_uri' property in current loop of arrayOfSongs.
- [x] Append each element to list element for each song.
- [x] Append each song to unordered list. 
- [x] Define a function pauseOthers to pause an audio file if a user presses play for another song. Set as callback function for 'play' event listener on each list/song element.
- [x] Define a function startNext to automatically start the next song in the list when current song has ended. Set as callback function for 'ended' event listener on each list/song element.
- [x] Define a function currentSongBorder to create a border around the current song triggering a 'playing' event listener for each song element.
- [x] Create a logo for the title of application using image from relative file path and a p tag underneath for text.
- [x] Add music note icon on other side of title in header.
- [x] Apply styling for both mobile and desktop views.
- [x] Remove all console log messages and commented code.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
