### ISSUE TITLE
Issue 2: User can browse songs by category

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/acnh-bgm#2]
## 💰 Functionality

User can browse collection of music in two separate orders: by time of day, or the weather/season in which the music plays during gameplay. 

## 🖼️ Wireframes

<img width="433" alt="image" src="https://user-images.githubusercontent.com/110082070/204975612-b0aa7f49-f282-4d3a-a4c0-7a05e4fb0829.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/110082070/204975486-0eb17054-7310-4aee-ba61-97809e73246a.png">

## ✅ Task List

- [x] Add to renderSongs function to create titles that separate different times of day inside unordered list. (Dawn / Dusk, Morning, Afternoon, Night)
- [x] Create a new div for separate class = 'home' view.
- [x] Create a new div with header "Select a category:" with same CSS styling as unordered list containing songs.
- [x] Center both time of day and weather icon elements in center of page underneath banner.
- [x] Create a new div for separate weather category view.
- [x] Create an event listener to listen for clicks for the cloud/weather icon, and the clock/time icon.
- [x] Make sure callback function for event listeners only changes views when not in the class='songs' view
- [x] Modify the renderSong function to check if view = 'time' or 'weather', where the view is a parameter defined by which icon is clicked.
- [x] Append collection of music by different order according to weather. (Sunny, Rainy, Snowy)
- [x] Create p tags for weather titles inside unordered list.
- [x] Add click event listener to header logo to show home page view.
- [x] Create function changeSongs to change the songs being rendered depending on which icon is clicked
- [x] Make sure changeSongs also changes the main icon being shown on top or on left side. 
- [x]  Apply styling for both mobile and desktop views.
- [x]  Remove all console log messages and commented code.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
