### ISSUE TITLE
Issue 3: User can add songs to a favorites page

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/acnh-bgm#3]
## 💰 Functionality

User can select a song by clicking the adjacent leaf icon, and see it appear in an unordered list for a new 'favorites' view that can be shown by clicking the music/playlist icon in the header. 

## 🖼️ Wireframes

<img width="465" alt="image" src="https://user-images.githubusercontent.com/110082070/205171388-2de7fa48-114f-4a9e-a1b3-9a553aeb9a17.png">
<img width="545" alt="image" src="https://user-images.githubusercontent.com/110082070/205234652-3131ce47-9ea2-48b2-a856-160e15e618fa.png">

## ✅ Task List

- [x] Create a new div class = 'favorites hidden' 
- [x] Add new icon with same class as playlist icon in header, including a p tag with text content 'Favorites' underneath, in the same style as time and weather icons.
- [x] Add a new unordered list with class favsongs containing a list item that will be removed when a song is added into the list. 
- [x] Add text content to list item: "Find your favorite daily background song!" with more instructions for use.
- [x] Add an event listener for the playlist icon in the header where the callback function removes 'hidden' class from favorites div and adds hidden class to other 'home' view and 'songs' view
- [x] Define a new function with similar functionality as renderSongs, but one that also adds arrow icons to the right side of the audio element each time a list element is appended. 
- [x] Modify CSS styling for new list to include spacing for the arrows on each song's right side.
- [x] Add CSS styling to indicate when elements are clickable.
