### ISSUE TITLE
Issue 4: User can delete songs from favorites page

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/acnh-bgm#4]
## 💰 Functionality

Users can delete songs they don't wish to hear anymore, or if there are more duplicates of one song than intended in the playlist.

## 🖼️ Wireframes

<img width="717" alt="image" src="https://user-images.githubusercontent.com/110082070/205359911-0abaa37f-c311-4785-b112-1e742e311095.png">

## ✅ Task List

- [x] Add a mouseover eventListener for when a leaf icon is hovered inside the favorites page
- [x] Replace specific leaf icon with a new delete icon.
- [x] Create new div in index.html, and give it classes modal and hidden.
- [x] Add click event listener for when a delete button is clicked inside the playlist.
- [x] When modal is present, set css style for body element's overflow to be hidden to prevent scrolling before a choice is made. 
- [x] In modal, ask user to confirm deletion of song or keep it. 
- [x] Replace hidden class for modal whenever a selection is made inside the modal.
- [x] Add click event listener for confirm button inside modal to remove song from playlist. 
- [x] Add CSS styling for modal and components inside
- [x] Add CSS styling to indicate whether a song can be added from any view outside of the favorites page.
- [x] Remove any unnecessary CSS styling.
