### ISSUE TITLE
Issue 5: User can edit order by moving song up or down list 

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/acnh-bgm#5]
## 💰 Functionality

Users can edit the order of their playlist by moving a song above its previous element, or below its next element. 

## 🖼️ Wireframes

<img width="488" alt="image" src="https://user-images.githubusercontent.com/110082070/205413866-f6e87c96-a488-4e87-b5b4-f3890f829697.png">

<img width="489" alt="image" src="https://user-images.githubusercontent.com/110082070/205413842-21faefda-2448-44fd-8034-08871cd96279.png">

## ✅ Task List

- [x] Add event listeners for small arrow icons.
- [x] Add class to CSS selector list to make sure cursor indicates the arrow is clickable.
- [x] Ensure that there are no errors when the down arrow is clicked for a song at the end of the list, and vice versa for the song on top of the list.
